export const products = {
   laptop: {
      id: 'laptop',
      name: 'Ноутбуки',
      icon: require('@/assets/img/icons/laptop.svg'),
      list: [
         {
            id: 1001,
            category: 'laptop',
            name: 'Ноутбук APPLE MacBook Pro, MV962RU/A, темно-серый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '2560х1600',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 8279U',
               'Процессор, частота': '2.4 ГГц (4.1 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR3, 2133 МГц',
               'Графический контроллер': 'Intel Iris graphics 655',
               'Объем SSD': '256 Гб',
            },
				price: 129990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/apple-spacegray.jpg')
         },
         {
            id: 1002,
            category: 'laptop',
            name: 'Ноутбук APPLE MacBook Pro, MV972RU/A, темно-серый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '2560х1600',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 8279U',
               'Процессор, частота': '2.4 ГГц (4.1 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR3, 2133 МГц',
               'Графический контроллер': 'Intel Iris graphics 655',
               'Объем SSD': '512 Гб',
            },
				price: 151910,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/apple-spacegray.jpg')
         },
         {
            id: 1003,
            category: 'laptop',
            name: 'Ноутбук APPLE MacBook Pro, Z0Z1000QD, серый',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '2560х1600',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 8557U',
               'Процессор, частота': '1.7 ГГц (4.5 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, LPDDR3, 2133 МГц',
               'Графический контроллер': 'Intel Iris graphics 645',
               'Объем SSD': '256 Гб',
            },
				price: 156690,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/apple-silver.jpg')
         },
         {
            id: 1004,
            category: 'laptop',
            name: 'Ноутбук APPLE MacBook Pro, Z0Z4000P1, серебристый',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '2560х1600',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 8557U',
               'Процессор, частота': '1.7 ГГц (4.5 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR3, 2133 МГц',
               'Графический контроллер': 'Intel Iris graphics 645',
               'Объем SSD': '512 Гб',
            },
				price: 160290,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/apple-silver.jpg')
         },
         {
            id: 1005,
            category: 'laptop',
            name: 'Ноутбук APPLE MacBook Pro, Z0Y1002DN, серебристый',
            core: 'i9',
            descr: {
               'Диагональ экрана в дюймах': '16 "',
               'Разрешение экрана': '3072×1920',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i9 9880H',
               'Процессор, частота': '2.4 ГГц (5.0 ГГц, в режиме Turbo)',
               'Оперативная память': '32768 Мб, DDR4, 2666 МГц',
               'Графический контроллер': 'Radeon Pro 5500M — 8192 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 265990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/apple.jpg')
         },
         {
            id: 1006,
            category: 'laptop',
            name: 'Ноутбук ASUS VivoBook S330FA-EY095, 90NB0KU3-M06600, серебристый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 8265U',
               'Процессор, частота': '1.6 ГГц (3.9 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR3',
               'Графический контроллер': 'Intel UHD Graphics 620',
               'Объем SSD': '256 Гб',
            },
				price: 47990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/asus-vivo.jpg')
         },
         {
            id: 1007,
            category: 'laptop',
            name: 'Ноутбук ASUS Zenbook UX325JA-EG109T, 90NB0QY1-M01750, серый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 1035G1',
               'Процессор, частота': '1.0 ГГц (3.6 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR4',
               'Графический контроллер': 'Intel UHD Graphics',
               'Объем SSD': '256 Гб',
            },
				price: 67290,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/asus-zen.jpg')
         },
         {
            id: 1008,
            category: 'laptop',
            name: 'Ультрабук ASUS ZenBook Duo UX481FL-BM021TS, 90NB0P61-M01520, синий',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '14 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 10510U',
               'Процессор, частота': '1.8 ГГц (4.9 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, LPDDR3',
               'Графический контроллер': 'nVidia GeForce MX250 — 2048 Мб',
               'Объем SSD': '1024 Гб',
            },
				price: 117790,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/asus-zen2.jpg')
         },
         {
            id: 1009,
            category: 'laptop',
            name: 'Ноутбук-трансформер HP Spectre x360 13-aw0002ur, 8KZ31EA, серебристый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 1035G4',
               'Процессор, частота': '1.1 ГГц (3.7 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR4, 3200 МГц',
               'Графический контроллер': 'Intel Iris Plus graphics',
               'Объем SSD': '512 Гб',
            },
				price: 99990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/hp-spectre.jpg')
         },
         {
            id: 1010,
            category: 'laptop',
            name: 'Ноутбук-трансформер HP EliteBook x360 830 G6, 6XD34EA, серебристый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 8265U',
               'Процессор, частота': '1.6 ГГц (3.9 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2400 МГц',
               'Графический контроллер': 'Intel UHD Graphics 620',
               'Объем SSD': '512 Гб',
            },
				price: 127290,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/hp-elite.jpg')
         },
         {
            id: 1011,
            category: 'laptop',
            name: 'Ноутбук HP Omen 17-cb1031ur, 22Y64EA, черный',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '17.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 10750H',
               'Процессор, частота': '2.6 ГГц (5.0 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2933 МГц',
               'Графический контроллер': 'NVIDIA GeForce RTX 2070 — 8192 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 124990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/hp-omen.jpg')
         },
         {
            id: 1012,
            category: 'laptop',
            name: 'Ноутбук HP Omen 15-dh1032ur, 22N22EA, черный',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '15.6 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 10750H',
               'Процессор, частота': '2.6 ГГц (5.0 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2933 МГц',
               'Графический контроллер': 'NVIDIA GeForce RTX 2080 SuperMQ — 8192 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 189990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/hp-omen2.jpg')
         },
         {
            id: 1013,
            category: 'laptop',
            name: 'Ноутбук LENOVO ThinkPad L13, 20R30009RT, черный',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 10210U',
               'Процессор, частота': '1.6 ГГц (4.2 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2666 МГц',
               'Графический контроллер': 'NVIDIA GeForce RTX 2080 SuperMQ — 8192 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 82870,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/lenovo-think.jpg')
         },
         {
            id: 1014,
            category: 'laptop',
            name: 'Ноутбук-трансформер LENOVO ThinkPad L13 Yoga, 20R5000ART, черный',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 10210U',
               'Процессор, частота': '1.6 ГГц (4.2 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2666 МГц',
               'Графический контроллер': 'Intel UHD Graphics',
               'Объем SSD': '512 Гб',
            },
				price: 96890,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/lenovo-yoga.jpg')
         },
         {
            id: 1015,
            category: 'laptop',
            name: 'Ноутбук LENOVO Legion 7 15IMH05, 81YT005DRU, серый',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '15.6 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 10750H',
               'Процессор, частота': '2.6 ГГц (5.0 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, DDR4, 2933 МГц',
               'Графический контроллер': 'NVIDIA GeForce RTX 2060 — 6144 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 142990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/lenovo-legion.jpg')
         },
         {
            id: 1016,
            category: 'laptop',
            name: 'Ноутбук LENOVO Yoga S940-14IIL, 81Q8002YRU, серый',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '14 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 1065G7',
               'Процессор, частота': '1.3 ГГц (3.9 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, LPDDR4, 3733 МГц',
               'Графический контроллер': 'Intel Iris Plus graphics',
               'Объем SSD': '1024 Гб',
            },
				price: 192290,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/lenovo-yoga2.jpg')
         },
         {
            id: 1017,
            category: 'laptop',
            name: 'Ноутбук DELL Vostro 5391, 5391-7155, серый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': '1.6 ГГц (4.2 ГГц, в режиме Turbo)',
               'Процессор, частота': '1.3 ГГц (3.9 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR3, 2133 МГц',
               'Графический контроллер': 'Intel UHD Graphics',
               'Объем SSD': '256 Гб',
            },
				price: 64390,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/dell-vostro.jpg')
         },
         {
            id: 1018,
            category: 'laptop',
            name: 'Ноутбук DELL Vostro 3490, 3490-9058, черный',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '14 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 10210U',
               'Процессор, частота': '1.6 ГГц (4.2 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, DDR4, 2666 МГц',
               'Графический контроллер': 'AMD Radeon 610 — 2048 Мб',
               'Объем SSD': '128 Гб',
            },
				price: 49680,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/dell-vostro2.jpg')
         },
         {
            id: 1019,
            category: 'laptop',
            name: 'Ультрабук DELL XPS 15, 9500-6017, серебристый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '15.6 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 10300H',
               'Процессор, частота': '2.5 ГГц (4.5 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, DDR4, 2933 МГц',
               'Графический контроллер': 'NVIDIA GeForce GTX 1650 Ti MAX Q — 4096 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 169100,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/dell-xps.jpg')
         },
         {
            id: 1020,
            category: 'laptop',
            name: 'Ноутбук DELL G7 7700, G717-2512, черный',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '17.3 "',
               'Разрешение экрана': '1920×1080',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 10750H',
               'Процессор, частота': '2.6 ГГц (5.0 ГГц, в режиме Turbo)',
               'Оперативная память': '32768 Мб, DDR4, 2933 МГц',
               'Графический контроллер': 'NVIDIA GeForce RTX 2070 Super — 8192 Мб',
               'Объем SSD': '1024 Гб',
            },
				price: 166770,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/dell-g7.jpg')
         },
         {
            id: 1021,
            category: 'laptop',
            name: 'Ультрабук ACER Swift 3 SF313-52-56L2, NX.HQWER.00A, серебристый',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '13.5 "',
               'Разрешение экрана': '2256×1504',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 1035G4',
               'Процессор, частота': '1.1 ГГц (3.7 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, LPDDR4',
               'Графический контроллер': 'Intel UHD Graphics',
               'Объем SSD': '512 Гб',
            },
				price: 66530,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/acer-swift.jpg')
         },
         {
            id: 1022,
            category: 'laptop',
            name: 'Ноутбук ACER Nitro 5 AN517-52-54AK, NH.Q8KER.006, черный',
            core: 'i5',
            descr: {
               'Диагональ экрана в дюймах': '17.3 "',
               'Разрешение экрана': '2256×1504',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i5 10300H',
               'Процессор, частота': '2.5 ГГц (4.5 ГГц, в режиме Turbo)',
               'Оперативная память': '8192 Мб, DDR4',
               'Графический контроллер': 'nVidia GeForce RTX 2060 — 6144 Мб',
               'Объем SSD': '512 Гб',
            },
				price: 96490,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/acer-nitro.jpg')
         },
         {
            id: 1023,
            category: 'laptop',
            name: 'Ультрабук ACER Swift 3 SF313-52G-79DX, NX.HR1ER.002, серый',
            core: 'i7',
            descr: {
               'Диагональ экрана в дюймах': '13.5 "',
               'Разрешение экрана': '2256×1504',
               'Тип матрицы': 'IPS',
               'Процессор': 'Intel Core i7 1065G7',
               'Процессор, частота': '1.3 ГГц (3.9 ГГц, в режиме Turbo)',
               'Оперативная память': '16384 Мб, LPDDR4',
               'Графический контроллер': '	nVidia GeForce MX350 — 2048 Мб',
               'Объем SSD': '1024 Гб',
            },
				price: 94790,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/acer-swift2.jpg')
         },
      ],
   },
   phone: {
      id: 'phone',
      name: 'Телефоны',
      icon: require('@/assets/img/icons/iphone.svg'),
      list: [
         {
            category: 'phone',
            id: 2001,
            name: 'Смартфон APPLE iPhone 7 32Gb, MN8X2RU/A, черный',
            memory: 32,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '4.7", Retina',
               'Разрешение экрана': '1334×750',
               'Процессор': 'Apple A10 Fusion, + Встроенный сопроцессор движения M10',
               'Объем встроенной памяти': '32 ГБ',
               'Размеры (ШхВхТ)': '67.1 х 138.3 х 7.1 мм',
               'Вес': '138 г',
            },
				price: 26990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-7-32-b.jpg')
         },
         {
            category: 'phone',
            id: 2002,
            name: 'Смартфон APPLE iPhone 8 64Gb, MQ6J2RU/A, белый',
            memory: 64,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '4.7", Retina',
               'Разрешение экрана': '1334×750',
               'Процессор': 'Apple A11 Bionic, + Встроенный сопроцессор движения М11',
               'Объем встроенной памяти': '64 ГБ',
               'Размеры (ШхВхТ)': '67.3 х 138.4 х 7.3 мм',
               'Вес': '148 г',
            },
				price: 30990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-8-64-w.jpg')
         },
         {
            category: 'phone',
            id: 2003,
            name: 'Смартфон APPLE iPhone X 256Gb «Как новый», FQAF2RU/A, серый',
            memory: 256,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '5.8',
               'Разрешение экрана': '2436×1125',
               'Процессор': 'Apple A11 Bionic, + Встроенный сопроцессор движения М11',
               'Объем встроенной памяти': '256 ГБ',
               'Размеры (ШхВхТ)': '70.9 х 143.6 х 7.7 мм',
               'Вес': '174 г',
            },
				price: 41990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-x-256-g.jpg')
         },
         {
            category: 'phone',
            id: 2004,
            name: 'Смартфон APPLE iPhone XR 128Gb, MRY92RU/A, черный',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.1", IPS',
               'Разрешение экрана': '1792×828',
               'Процессор': 'Apple A12 Bionic',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '75.7 х 150.9 х 8.3 мм',
               'Вес': '194 г',
            },
				price: 51490,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-xr-128-b.jpg')
         },
         {
            category: 'phone',
            id: 2005,
            name: 'Смартфон APPLE iPhone XS MAX 64Gb, FT502RU/A, серый космос',
            memory: 64,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.5", OLED',
               'Разрешение экрана': '2688×1242',
               'Процессор': 'Apple A12 Bionic',
               'Объем встроенной памяти': '64 ГБ',
               'Размеры (ШхВхТ)': '77.4 х 157.5 х 7.7 мм',
               'Вес': '208 г',
            },
				price: 58990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-xs-64-sg.jpg')
         },
         {
            category: 'phone',
            id: 2006,
            name: 'Смартфон APPLE iPhone 11 128Gb, MWM62RU/A, зеленый',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.1", IPS',
               'Разрешение экрана': '1792×828',
               'Процессор': 'Apple A13 Bionic',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '75.7 х 150.9 х 8.3 мм',
               'Вес': '194 г',
            },
				price: 59990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-11-128-g.jpg')
         },
         {
            category: 'phone',
            id: 2007,
            name: 'Смартфон APPLE iPhone 12 128Gb, MGJD3RU/A, красный',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.1", IPS',
               'Разрешение экрана': '2532×1170',
               'Процессор': 'Apple A14 Bionic',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '71.5 х 146.7 х 7.4 мм',
               'Вес': '162 г',
            },
				price: 84990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-12-128-r.jpg')
         },
         {
            category: 'phone',
            id: 2008,
            name: 'Смартфон APPLE iPhone SE 2020 128Gb, MXD02RU/A, черный',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '4.7", IPS',
               'Разрешение экрана': '1334×750',
               'Процессор': 'Apple A13 Bionic',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '71.5 х 146.7 х 7.4 мм',
               'Вес': '162 г',
            },
				price: 42990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/iphone-se-128-b.jpg')
         },
         {
            category: 'phone',
            id: 2009,
            name: 'Смартфон SAMSUNG Galaxy S20 8/128Gb, SM-G980F, серый',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.2", Dynamic AMOLED',
               'Разрешение экрана': '3200×1440',
               'Процессор': 'Exynos 990, , 8-ми ядерный',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '69.1 х 151.7 х 7.9 мм',
               'Вес': '163 г',
            },
				price: 57990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-s20-128-g.jpg')
         },
         {
            category: 'phone',
            id: 2010,
            name: 'Смартфон SAMSUNG Galaxy A71 128Gb, SM-A715F, серебристый',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.7", Super AMOLED',
               'Разрешение экрана': '2400×1080',
               'Процессор': 'Qualcomm Snapdragon 730, 2200МГц, 8-ми ядерный',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '76 х 163.6 х 7.7 мм',
               'Вес': '179 г',
            },
				price: 27599,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-a71-128-s.jpg')
         },
         {
            category: 'phone',
            id: 2011,
            name: 'Смартфон SAMSUNG Galaxy A71 128Gb, SM-A715F, серебристый',
            memory: 32,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.2", TFT',
               'Разрешение экрана': '1520×720',
               'Процессор': 'Exynos 7884B, 1600МГц, 8-ми ядерный',
               'Объем встроенной памяти': '32 ГБ',
               'Размеры (ШхВхТ)': '75.6 х 155.6 х 7.9 мм',
               'Вес': '166 г',
            },
				price: 7990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-a10-32-b.jpg')
         },
         {
            category: 'phone',
            id: 2012,
            name: 'Смартфон SAMSUNG Galaxy Note 20 Ultra 256Gb, SM-N985F, бронзовый',
            memory: 256,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.9", Dynamic AMOLED 2X',
               'Разрешение экрана': '3088×1440',
               'Процессор': 'Exynos 990, 8-ми ядерный',
               'Объем встроенной памяти': '256 ГБ',
               'Размеры (ШхВхТ)': '77.2 х 164.8 х 8.1 мм',
               'Вес': '208 г',
            },
				price: 89990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-note20-256-b.jpg')
         },
         {
            category: 'phone',
            id: 2013,
            name: 'Смартфон SAMSUNG Galaxy S10+ 128Gb, SM-G975F, черный',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.4", AMOLED',
               'Разрешение экрана': '2960×1440',
               'Процессор': 'Exynos 9820, 8-ми ядерный',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '74.1 х 157.6 х 7.8 мм',
               'Вес': '175 г',
            },
				price: 49990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-s10-128-b.jpg')
         },
         {
            category: 'phone',
            id: 2014,
            name: 'Смартфон SAMSUNG Galaxy A21s 32Gb, SM-A217F, синий',
            memory: 32,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.5", LCD',
               'Разрешение экрана': '1600×720',
               'Процессор': 'Exynos 850, 2000МГц, 8-ми ядерный',
               'Объем встроенной памяти': '32 ГБ',
               'Размеры (ШхВхТ)': '75.3 х 163.7 х 8.9 мм',
               'Вес': '192 г',
            },
				price: 13799,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-a21-32-b.jpg')
         },
         {
            category: 'phone',
            id: 2015,
            name: 'Смартфон SAMSUNG Galaxy A21s 32Gb, SM-A217F, синий',
            memory: 128,
            descr: {
               'Класс': 'смартфон',
               'Дисплей': '6.2", Dynamic AMOLED',
               'Разрешение экрана': '3200×1440',
               'Процессор': 'Exynos 990, 8-ми ядерный',
               'Объем встроенной памяти': '128 ГБ',
               'Размеры (ШхВхТ)': '69.1 х 151.7 х 7.9 мм',
               'Вес': '163 г',
            },
				price: 57990,
				discount: 0,
				amount: 1,
            inCart: false,
            img: require('@/assets/img/products/samsung-s20-128-r.jpg')
         }
      ]
   }
}